### ISSUE TITLE
File not find

### ISSUE THREAD

**Issue by jyli559** [hkust-zhiyao/MasterRTL#2]
Hello, when I got to this

Power
$ cd preproc/power
$ python3 tr_propagate.py
, the command "file not found" came up again : No such file or directory: './design_hier.json'
and I realized that the file was indeed there, so what should I do?
This also occurs in the following

Timing
$ cd feature_extract/timing
$ python3 feature_extra_graph_STA.py
I got : No such file or directory: '../../example/timing_dag/node_dict_update/TinyRocket_sog_node_dict_init.pkl'

**Comment by fangwenji** [comment]
Sorry for the late response. 

For the power part, I've uploaded a correct example of the JSON file, thanks for the correction. Please note that the feature extraction for module power needs the toggle rate information obtained from the EDA tool (e.g., Design Compiler) at the beginning of the logic synthesis process. 

For the timing part, I've fixed bugs in delay_propagation.py in the preproc step, please re-run the Python code, so that the file can be generated. Please also note that this feature extraction for timing needs the trained path-level model ('rfr' in the code) to infer the path delay. You may train the path model first referring to the method in the paper.
